on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       repository: ${{ github.repository }}
       tag_with_ref: true
       tag_with_sha: true
       tags: ${{ github.sha }}

   # - name: Check if URL is valid
   #   uses: ubuntu-latest
   #   run: |
   #     echo "URL is: ${{ steps.getNgrokUrl.outputs.url }}"
     # - name: Watch ngrok
     # uses: steebchen/kubectl@master
     # env:
     #   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
     #   KUBECTL_VERSION: "1.20"
     # run: echo "Hello world"
     # with:
     #   args: '"rollout status deployment/my-app"'
     
